// gen-ksi-doc.mjs — generate docs/01-ksi-reference.md, the KSI rule set, from the catalog.
// The reference is generated so it cannot drift from ontology/ksi-catalog.json.
// Run:  node tools/gen-ksi-doc.mjs           (writes docs/01-ksi-reference.md)
//       node tools/gen-ksi-doc.mjs --check   (exits 1 if the committed file is stale)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..');
const cat = JSON.parse(readFileSync(join(ROOT, 'ontology/ksi-catalog.json'), 'utf8'));

const ORIGIN = { CR26: 'FedRAMP CR26', DIB: 'DIB-native', 'DIB-D': 'Class-D/L3 module (800-172)' };

const classLine = (c) => {
  const vals = ['A', 'B', 'C', 'D'].map((x) => c[x] || 'n/a');
  if (new Set(vals).size === 1) return `${vals[0]} at every class`;
  return ['A', 'B', 'C', 'D'].map((x, i) => `${x} ${vals[i]}`).join(' · ');
};
const levelLine = (l) => ['L1', 'L2', 'L3'].filter((x) => l[x]).join(' ');

const L = [];
const p = (s) => L.push(s);

const uplift = cat.ksis.filter((k) => k.uplift);
const nonDef = cat.ksis.filter((k) => k.non_deferrable);
const fams = {};
for (const k of cat.ksis) (fams[k.family] ||= []).push(k);

p('# The KSI reference');
p('');
p('Generated by `tools/gen-ksi-doc.mjs` from `ontology/ksi-catalog.json`. Do not edit by hand; edit the catalog and regenerate.');
p('');
p(`Catalog version \`${cat.version}\`, dated \`${cat.date}\`. ${cat.ksis.length} key security indicators across ${Object.keys(fams).length} families.`);
p('');
p('The catalog protects one thing: the confidentiality of CUI. Levels decide which requirements apply (CMMC L1/L2/L3, unchanged). Classes decide how much proof (A cheapest, D deepest). Every KSI applies to any DIB organization whose scope includes it, at any size; the deployment profiles in `ontology/responsibility-patterns.json` decide who runs each one.');
p('');
p('Each entry carries:');
p('');
p('- **Statement** — what must be true.');
p('- **CUI confidentiality** — how the KSI protects CUI from disclosure. Where a KSI is not a confidentiality control, the line says so instead of implying otherwise.');
p(`- **Classes / levels / 800-171 r2 mapping** — where it applies and what it satisfies. ${cat.ksis.filter((k) => k.rev2_requirements.length).length} KSIs map to 800-171 r2 requirements; the rest are unmapped by design (uplift or scope machinery).`);
p('');
p(`**Uplift (${uplift.length} KSIs).** Beyond the 800-171 confidentiality floor — availability, integrity, or program maturity. Never required below Class D, never affecting level compliance; reported for CR26/Class-C reciprocity. Marked ↑.`);
p('');
p(`**Non-deferrable (${nonDef.length} KSIs).** Crown-jewel indicators flagged ◆. The flag is informational; exception eligibility binds at the requirement level per 32 CFR 170.21.`);
p('');

for (const [fam, ks] of Object.entries(fams).sort()) {
  p(`## ${fam} — ${ks[0].family_name} (${ks.length})`);
  p('');
  for (const k of ks) {
    const flags = [k.uplift ? '↑' : '', k.non_deferrable ? '◆' : ''].filter(Boolean).join(' ');
    p(`### ${k.id} — ${k.name}${flags ? ' ' + flags : ''}`);
    p('');
    p(k.statement);
    p('');
    p(`**CUI confidentiality:** ${k.cui_impact}`);
    p('');
    const facts = [
      `Classes: ${classLine(k.classes)}`,
      `Levels: ${levelLine(k.levels)}`,
      `800-171 r2: ${k.rev2_requirements.length ? k.rev2_requirements.join(', ') : 'unmapped'}`,
      k.automatable ? 'automatable' : 'physical/procedural',
      `origin: ${ORIGIN[k.origin]}`,
    ];
    p(facts.join(' · '));
    p('');
  }
}

const out = L.join('\n');
const target = join(ROOT, 'docs/01-ksi-reference.md');
if (process.argv.includes('--check')) {
  let cur = '';
  try { cur = readFileSync(target, 'utf8'); } catch { }
  if (cur !== out) { console.error('STALE: docs/01-ksi-reference.md is out of date. Run: node tools/gen-ksi-doc.mjs'); process.exit(1); }
  console.log('IN SYNC — docs/01-ksi-reference.md matches the catalog.');
} else {
  writeFileSync(target, out);
  console.log(`built docs/01-ksi-reference.md — ${L.length} lines`);
}
