// gen-summary.mjs — generate COMPONENTS.md, the component index, from the registries themselves.
// The index is generated so it cannot drift from what the repository actually contains.
// Run:  node tools/gen-summary.mjs           (writes COMPONENTS.md)
//       node tools/gen-summary.mjs --check   (exits 1 if the committed file is stale)
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..');
const rd = p => JSON.parse(readFileSync(join(ROOT, p), 'utf8'));

const ont = rd('ontology/dib-ksi-ontology.json');
const sig = rd('ontology/signals.json');
const pat = rd('ontology/responsibility-patterns.json');
const poam = rd('ontology/poam-policy.json');
const cat = rd('ontology/ksi-catalog.json');

const count = d => { try { return readdirSync(join(ROOT, d)).filter(f => !f.startsWith('.')).length; } catch { return 0; } };
const L = [];
const p = s => L.push(s);

p('# Components');
p('');
p('Generated by `tools/gen-summary.mjs`. Do not edit by hand; edit the registries and regenerate.');
p('');
p(`Dataset version \`${ont.version}\`, released \`${ont.date}\`.`);
p('');

p('## Registries — the source of truth');
p('');
p('| Component | Version | Contents |');
p('|---|---|---|');
p(`| \`ontology/dib-ksi-ontology.json\` | ${ont.version} | ${Object.keys(ont.entities).length} entity types across ${Object.keys(ont.layers).length} layers, ${ont.relations.length} relations, ${ont.invariants.length} invariants, ${ont.projections.length} projections |`);
p(`| \`ontology/signals.json\` | ${sig.version} | ${sig.signals.length} measurable indicators with per-class thresholds and cadence |`);
p(`| \`ontology/responsibility-patterns.json\` | ${pat.version} | ${pat.assignments.length} responsibility assignments across ${Object.keys(pat.profiles).length} deployment profiles, plus the three-test inheritance rule |`);
p(`| \`ontology/poam-policy.json\` | ${poam.version} | Requirement-level exception eligibility (${poam.status.split('—')[0].trim()}) |`);
p(`| \`ontology/ksi-catalog.json\` | ${cat.version} | ${cat.ksis.length} key security indicators across ${new Set(cat.ksis.map(k => k.family)).size} families |`);
p('');

p('## The five ontology layers');
p('');
p('| Layer | Purpose |');
p('|---|---|');
for (const [k, v] of Object.entries(ont.layers)) p(`| \`${k}\` | ${v} |`);
p('');

p('## Invariants');
p('');
p('Each is enforced by the validator and carries a negative test that fails without it.');
p('');
p('| ID | Statement |');
p('|---|---|');
for (const i of ont.invariants) p(`| \`${i.id}\` | ${i.statement} |`);
p('');

p('## Projections');
p('');
p('Every deliverable is a query over the graph. None is stored.');
p('');
p('| ID | Deliverable |');
p('|---|---|');
for (const x of ont.projections) p(`| \`${x.id}\` | ${x.name} |`);
p('');

p('## Indicators');
p('');
p('| ID | Indicator | Shape | Authority | Validates |');
p('|---|---|---|---|---|');
for (const s of sig.signals) {
  const auth = s.authority ? `\`${s.authority.policy_id}\`` : '_local policy_';
  p(`| \`${s.id}\` | ${s.name} | ${s.kind} | ${auth} | ${s.validates.join(', ')} |`);
}
p('');
p(`${sig.signals.filter(s => s.authority).length} of ${sig.signals.length} indicators cite an external authority. The rest are this project's own policy choices and say so per signal.`);
p('');

p('## Plain-language guidance');
p('');
{
  const g = JSON.parse(readFileSync(join(ROOT, 'ontology/guidance.json'), 'utf8'));
  const by = Object.fromEntries(pat.assignments.map((a) => [a.ksi, a]));
  const owned = cat.ksis.filter((k) => {
    const st = (k.classes || {}).B; return st && st !== 'n/a' && by[k.id]['enclave-only'] === 'tenant';
  });
  const n = Object.keys(g.guidance).length;
  p(`Each covered indicator answers four questions in plain language: what is actually being asked, what being able to say yes looks like, what you would hand over, and how the check runs without a person.`);
  p('');
  p(`Written for ${n} of ${cat.ksis.length} indicators — the ${owned.length} a small contractor owns alone under the enclave-only profile. The rest are shared with or inherited from a provider, so the provider drives them.`);
  p('');
}

p('## KSI families');
p('');
p('| Family | KSIs | Automatable | Not automatable |');
p('|---|---|---|---|');
const fam = {};
for (const k of cat.ksis) (fam[k.family] ||= []).push(k);
for (const [f, ks] of Object.entries(fam).sort())
  p(`| ${f} | ${ks.length} | ${ks.filter(k => k.automatable).length} | ${ks.filter(k => !k.automatable).length} |`);
p(`| **Total** | **${cat.ksis.length}** | **${cat.ksis.filter(k => k.automatable).length}** | **${cat.ksis.filter(k => !k.automatable).length}** |`);
p('');

p('## Deployment profiles');
p('');
p('Read per class. The full catalogue applies only at Class D, so a single figure over all 64 indicators silently assumes the deepest class.');
p('');
const byKsi = Object.fromEntries(pat.assignments.map((a) => [a.ksi, a]));
for (const [id, prof] of Object.entries(pat.profiles)) {
  p(`**${prof.name}**`);
  p('');
  p('| Class | In scope | Inherited | N/A | Shared | Tenant-only | Off the tenant |');
  p('|---|---|---|---|---|---|---|');
  for (const cls of ['A', 'B', 'C', 'D']) {
    const inScope = cat.ksis.filter((k) => {
      const st = (k.classes || {})[cls];
      return st && st !== 'n/a';
    });
    const t = {};
    for (const k of inScope) {
      const mode = byKsi[k.id]?.[id] ?? 'tenant';
      t[mode] = (t[mode] || 0) + 1;
    }
    const off = (t.inherited || 0) + (t.not_applicable || 0);
    p(`| ${cls} | ${inScope.length} | ${t.inherited || 0} | ${t.not_applicable || 0} | ${t.shared || 0} | ${t.tenant || 0} | **${off} (${Math.round(off / inScope.length * 100)}%)** |`);
  }
  p('');
}
p('Tenant-only work stays close to flat as the class rises while shared work grows. Climbing a class deepens proof on shared work rather than adding work the tenant carries alone.');
p('');

p('## Directories');
p('');
p('| Path | Files | Contents |');
p('|---|---|---|');
const DIRS = [
  ['ontology/', 'The registries above, the collector registry, and the requirement coverage crosswalk'],
  ['instances/', 'Worked instance graphs'],
  ['tools/', 'Validator, projection engine, generators, tests, prose lint, CI'],
  ['docs/', 'Why the framework exists and how it works'],
  ['site/', 'The overview, the self-assessment, and the reference tool, generated from the registries'],
];
for (const [d, desc] of DIRS) p(`| \`${d}\` | ${count(d)} | ${desc} |`);
p('');

const out = L.join('\n');
const target = join(ROOT, 'COMPONENTS.md');
if (process.argv.includes('--check')) {
  let cur = '';
  try { cur = readFileSync(target, 'utf8'); } catch { }
  if (cur !== out) { console.error('STALE: COMPONENTS.md is out of date. Run: node tools/gen-summary.mjs'); process.exit(1); }
  console.log('IN SYNC — COMPONENTS.md matches the registries.');
} else {
  writeFileSync(target, out);
  console.log(`built COMPONENTS.md — ${L.length} lines`);
}
