#!/usr/bin/env node
// Inject the canonical registries into the published pages.
//
// The pages under site/ are committed HTML, but the data they render is not
// hand-maintained. This rewrites the block between the DIB-DATA markers from
// ontology/, so a page cannot quietly disagree with the registry it describes.
// CI step 9 re-runs this and fails if anything moved, which makes drift a build
// error rather than something a reader discovers.
//
// Run: node tools/gen-pages.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const rd = (p) => JSON.parse(readFileSync(resolve(root, p), 'utf8'));

const catalog   = rd('ontology/ksi-catalog.json');
const signals   = rd('ontology/signals.json');
const collection = rd('ontology/collection.json');
const ontology  = rd('ontology/dib-ksi-ontology.json');
const patterns  = rd('ontology/responsibility-patterns.json');
const guidance  = rd('ontology/guidance.json');

// ── Derive the enclave split per class rather than hardcoding it ────────────
// The README and docs quote these numbers; computing them here means the pages,
// the docs, and the registry cannot disagree.
const byKsi = Object.fromEntries(patterns.assignments.map((a) => [a.ksi, a]));
const enclave = {};
for (const profile of Object.keys(patterns.profiles)) {
  enclave[profile] = {};
  for (const cls of ['A', 'B', 'C', 'D']) {
    const inScope = catalog.ksis.filter((k) => {
      const s = (k.classes || {})[cls];
      return s && s !== 'n/a';
    });
    const tally = { inherited: 0, not_applicable: 0, shared: 0, tenant: 0 };
    for (const k of inScope) {
      const mode = byKsi[k.id]?.[profile] ?? 'tenant';
      tally[mode] = (tally[mode] ?? 0) + 1;
    }
    const off = tally.inherited + tally.not_applicable;
    enclave[profile][cls] = {
      in_scope: inScope.length,
      ...tally,
      off_tenant: off,
      off_pct: Math.round((off / inScope.length) * 100),
    };
  }
}

const payload = [
  `const CAT=${JSON.stringify(catalog)};`,
  `const SIG=${JSON.stringify({ version: signals.version, signals: signals.signals })};`,
  `const COL=${JSON.stringify(collection)};`,
  `const INV=${JSON.stringify(ontology.invariants)};`,
  `const SCN=${JSON.stringify(ontology.scenarios)};`,
  `const EVD=${JSON.stringify(ontology.evidence_types)};`,
  `const ENCL=${JSON.stringify({ profiles: patterns.profiles, split: enclave })};`,
  `const WORK=${JSON.stringify(ontology.working_sets)};`,
  `const GUIDE=${JSON.stringify(guidance.guidance)};`,
  `const PAT=${JSON.stringify({ profiles: patterns.profiles, assignments: patterns.assignments })};`,
].join('\n');

const START = '/*==DIB-DATA-START==';
const END = '/*==DIB-DATA-END==*/';

let changed = 0;
for (const page of ['site/reference.html', 'site/index.html', 'site/assess.html']) {
  const path = resolve(root, page);
  let html;
  try { html = readFileSync(path, 'utf8'); } catch { continue; }

  const a = html.indexOf(START);
  const b = html.indexOf(END);
  if (a === -1 || b === -1) continue;   // page carries no data block

  const header = `${START} generated by tools/gen-pages.mjs from ontology/ — do not hand-edit ==*/\n`;
  const next = html.slice(0, a) + header + payload + '\n' + html.slice(b);

  if (next !== html) { writeFileSync(path, next); changed++; console.log(`  rewrote ${page}`); }
  else console.log(`  ${page} already current`);
}

const bound = signals.signals.filter((s) => s.authority).length;
console.log(
  `PAGES OK — ${catalog.ksis.length} KSIs, ${signals.signals.length} measurements ` +
  `(${bound} authority-bound), ${collection.methods.length} collection methods, ` +
  `${ontology.invariants.length} invariants; ${changed} file(s) rewritten`
);
